# Generated by Django 3.0.8 on 2020-07-09 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200709_0308'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingAddress',
            new_name='DeliveryAddress',
        ),
        migrations.RenameField(
            model_name='deliveryaddress',
            old_name='state',
            new_name='street',
        ),
        migrations.RenameField(
            model_name='deliveryaddress',
            old_name='zipcode',
            new_name='township',
        ),
    ]
