# Generated by Django 3.0.8 on 2020-07-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20200709_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='complete',
            field=models.CharField(default='incomplete', max_length=200),
        ),
    ]
